name: Daily Commit Update

on:
  schedule:
    - cron: '0 10 * * *'  # This runs the workflow every day at 10:00 AM UTC. Adjust as necessary.
    
jobs:
  daily_commit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Make a commit with email 21f1006915@ds.study.iitm.ac.in
      run: |
        echo "Updating repository with a daily commit" >> daily_update.txt
        git config user.name "DevSync Bot"
        git config user.email "21f1006915@ds.study.iitm.ac.in"
        git add daily_update.txt
        git commit -m "Daily commit update"
        git push
