name: Daily Commit Update

on:
  schedule:
    - cron: '0 10 * * *'  # This runs the workflow every day at 10:00 AM UTC. Adjust as necessary.

jobs:
  daily_commit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Make a commit with email 21f1006915@ds.study.iitm.ac.in
      run: |
        # Make sure the file exists, or create it if it doesn't
        if [ ! -f daily_update.txt ]; then
          echo "This is an automated daily update" > daily_update.txt
        else
          echo "Appending automated daily update" >> daily_update.txt
        fi
        
        # Set Git configuration
        git config user.name "DevSync Bot"
        git config user.email "21f1006915@ds.study.iitm.ac.in"
        
        # Stage changes
        git add daily_update.txt
        
        # Commit changes
        git commit -m "Daily commit update" || echo "No changes to commit"

        # Push changes to the repository
        git push
