name: Run Test Action

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: 21f1006915@ds.study.iitm.ac.in
        run: echo "Hello, world!"
